### ISSUE TITLE
Create a folder called "doc" and add a file called "how_to.md"

### ISSUE THREAD

**Issue by amichai-bd** [yonibenda/ybd_playground#6]
In the how_to.md file you should document:
1. all the links you used to get the programs. (git, vscode)
2. under a "bash command" header, add a list of commands you learned.
3. under a "git command" header, add a list of git commands you learned. -> add an example of a "common" flow. pull, change, commit, push.

**Comment by yonibenda** [comment]
i've created cheat sheets insted .
